# Generated by Django 4.2.1 on 2023-05-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_myuser_password_alter_myuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
